SUPABASE_URL="https://wsmexeffxhkvelmcaspy.supabase.co"
SUPABASE_KEY="sb_publishable_6KqW1JI1GWBE6_4zDMoxRg_vUrpQWf2"
EMAILJS_SERVICE_ID = "service_portfolio"
EMAILJS_TEMPLATE_ID = "template_8944mri"
EMAILJS_PUBLIC_KEY = "0Hu3CKVVdwfLua7nA"
EMAILJS_PRIVATE_KEY = "LFjJe4BbLslL5eMnv-iW3"
